name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
    
      - name: build
        run: dotnet build -c Release

      - name: test
        run: dotnet test --no-build -c Release

      - name: publish
        run: dotnet publish --no-build -p:PublishDir=/dist source/Mono.API/Mono.API.csproj

